Update sync-deploy-verify.yml

diff --git a/.github/workflows/sync-deploy-verify.yml b/.github/workflows/sync-deploy-verify.yml
--- a/.github/workflows/sync-deploy-verify.yml
+++ b/.github/workflows/sync-deploy-verify.yml
@@ -76,7 +76,18 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ contains( fromJson('["dev", "uat", "stage", "main"]'), inputs.BRANCH)  && github.event_name != 'pull_request' }} 
     steps:
+      - name: Check deployment comments
+        id: comments
+        uses: ./.github/actions/validate-cr-comments
+
+      - name: Fail if Comment is Invalid
+        if: steps.comments.outputs.valid == 'false'
+        run: |
+          echo "Deployment comment does not contain a Change Request number. Aborting deployment."
+          exit 1
+          
       - name: deploy to ${{ inputs.ENVIRONMENT }}
+        if: steps.check_comment.outputs.valid == 'true'
         run: |
           echo "deploying to ${{ inputs.ENVIRONMENT  }}"
           
